CREATE TABLE "billing_periods" (
	"id" text PRIMARY KEY NOT NULL,
	"company_id" text NOT NULL,
	"project_id" text NOT NULL,
	"number" integer NOT NULL,
	"reference" text NOT NULL,
	"name" text NOT NULL,
	"status" text DEFAULT 'open' NOT NULL,
	"start_date" text NOT NULL,
	"end_date" text NOT NULL,
	"billing_date" text NOT NULL,
	"subcontractor_submit_start" text,
	"subcontractor_submit_end" text,
	"owner_billing_date" text,
	"due_date" text,
	"owner_billed_amount" double precision DEFAULT 0 NOT NULL,
	"subcontractor_billed_amount" double precision DEFAULT 0 NOT NULL,
	"retainage_held_amount" double precision DEFAULT 0 NOT NULL,
	"retainage_released_amount" double precision DEFAULT 0 NOT NULL,
	"invoice_count" integer DEFAULT 0 NOT NULL,
	"closed_at" timestamp with time zone,
	"closed_by" text,
	"locked_at" timestamp with time zone,
	"locked_by" text,
	"notes" text,
	"detail" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_by" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "budget_changes" (
	"id" text PRIMARY KEY NOT NULL,
	"company_id" text NOT NULL,
	"project_id" text NOT NULL,
	"budget_id" text NOT NULL,
	"number" integer NOT NULL,
	"reference" text NOT NULL,
	"kind" text DEFAULT 'transfer' NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"reason" text,
	"status" text DEFAULT 'draft' NOT NULL,
	"lines" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"from_line_item_id" text,
	"to_line_item_id" text,
	"amount" double precision DEFAULT 0 NOT NULL,
	"net_effect" double precision DEFAULT 0 NOT NULL,
	"effective_date" text,
	"source_type" text,
	"source_id" text,
	"requested_by" text NOT NULL,
	"requested_at" timestamp with time zone,
	"approved_by" text,
	"approved_at" timestamp with time zone,
	"rejected_by" text,
	"rejected_at" timestamp with time zone,
	"rejection_reason" text,
	"detail" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_by" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "budget_forecasts" (
	"id" text PRIMARY KEY NOT NULL,
	"company_id" text NOT NULL,
	"project_id" text NOT NULL,
	"budget_id" text NOT NULL,
	"line_item_id" text,
	"billing_period_id" text,
	"number" integer NOT NULL,
	"reference" text NOT NULL,
	"as_of_date" text NOT NULL,
	"method" text DEFAULT 'manual' NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"forecast_to_complete" double precision DEFAULT 0 NOT NULL,
	"forecast_final" double precision DEFAULT 0 NOT NULL,
	"previous_forecast_final" double precision DEFAULT 0 NOT NULL,
	"delta_from_previous" double precision DEFAULT 0 NOT NULL,
	"percent_complete" double precision DEFAULT 0 NOT NULL,
	"curve" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"assumptions" text,
	"notes" text,
	"detail" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_by" text NOT NULL,
	"submitted_by" text,
	"submitted_at" timestamp with time zone,
	"approved_by" text,
	"approved_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "budget_line_items" (
	"id" text PRIMARY KEY NOT NULL,
	"budget_id" text NOT NULL,
	"company_id" text NOT NULL,
	"project_id" text NOT NULL,
	"cost_code_id" text,
	"cost_code" text NOT NULL,
	"cost_type" text DEFAULT 'other' NOT NULL,
	"wbs_path" text,
	"sub_job" text,
	"description" text NOT NULL,
	"line_kind" text DEFAULT 'standard' NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"unit" text,
	"quantity" double precision,
	"unit_rate" double precision,
	"original_budget" double precision DEFAULT 0 NOT NULL,
	"budget_modifications" double precision DEFAULT 0 NOT NULL,
	"approved_changes" double precision DEFAULT 0 NOT NULL,
	"pending_budget_changes" double precision DEFAULT 0 NOT NULL,
	"revised_budget" double precision DEFAULT 0 NOT NULL,
	"committed_cost" double precision DEFAULT 0 NOT NULL,
	"pending_commitments" double precision DEFAULT 0 NOT NULL,
	"direct_costs" double precision DEFAULT 0 NOT NULL,
	"job_to_date_costs" double precision DEFAULT 0 NOT NULL,
	"forecast_method" text DEFAULT 'remaining_budget' NOT NULL,
	"forecast_to_complete" double precision DEFAULT 0 NOT NULL,
	"forecast_final" double precision DEFAULT 0 NOT NULL,
	"projected_over_under" double precision DEFAULT 0 NOT NULL,
	"percent_complete" double precision DEFAULT 0 NOT NULL,
	"notes" text,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"detail" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_by" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "budget_snapshots" (
	"id" text PRIMARY KEY NOT NULL,
	"company_id" text NOT NULL,
	"project_id" text NOT NULL,
	"budget_id" text NOT NULL,
	"number" integer NOT NULL,
	"reference" text NOT NULL,
	"name" text NOT NULL,
	"kind" text DEFAULT 'monthly_close' NOT NULL,
	"billing_period_id" text,
	"period_start" text,
	"period_end" text,
	"as_of_date" text NOT NULL,
	"lines" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"totals" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"content_hash" text NOT NULL,
	"line_count" integer DEFAULT 0 NOT NULL,
	"notes" text,
	"detail" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"captured_by" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "budgets" (
	"id" text PRIMARY KEY NOT NULL,
	"company_id" text NOT NULL,
	"project_id" text NOT NULL,
	"number" integer NOT NULL,
	"reference" text NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"status" text DEFAULT 'draft' NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"is_active" integer DEFAULT 0 NOT NULL,
	"currency" text DEFAULT 'USD' NOT NULL,
	"wbs_segment_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"locked_at" timestamp with time zone,
	"locked_by" text,
	"original_budget_total" double precision DEFAULT 0 NOT NULL,
	"budget_modifications_total" double precision DEFAULT 0 NOT NULL,
	"approved_changes_total" double precision DEFAULT 0 NOT NULL,
	"pending_changes_total" double precision DEFAULT 0 NOT NULL,
	"revised_budget_total" double precision DEFAULT 0 NOT NULL,
	"committed_total" double precision DEFAULT 0 NOT NULL,
	"pending_commitments_total" double precision DEFAULT 0 NOT NULL,
	"direct_costs_total" double precision DEFAULT 0 NOT NULL,
	"job_to_date_costs_total" double precision DEFAULT 0 NOT NULL,
	"forecast_to_complete_total" double precision DEFAULT 0 NOT NULL,
	"forecast_final_total" double precision DEFAULT 0 NOT NULL,
	"variance_total" double precision DEFAULT 0 NOT NULL,
	"totals_calculated_at" timestamp with time zone,
	"settings" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"detail" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_by" text NOT NULL,
	"approved_by" text,
	"approved_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "change_events" (
	"id" text PRIMARY KEY NOT NULL,
	"company_id" text NOT NULL,
	"project_id" text NOT NULL,
	"number" integer NOT NULL,
	"reference" text NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"status" text DEFAULT 'open' NOT NULL,
	"event_type" text DEFAULT 'other' NOT NULL,
	"scope" text DEFAULT 'tbd' NOT NULL,
	"reason" text,
	"origin_type" text DEFAULT 'manual' NOT NULL,
	"origin_id" text,
	"prime_contract_id" text,
	"location_id" text,
	"tier" text,
	"rough_order_of_magnitude" double precision DEFAULT 0 NOT NULL,
	"estimated_cost" double precision DEFAULT 0 NOT NULL,
	"latest_cost" double precision DEFAULT 0 NOT NULL,
	"estimated_revenue" double precision DEFAULT 0 NOT NULL,
	"approved_revenue" double precision DEFAULT 0 NOT NULL,
	"schedule_impact_days" integer DEFAULT 0 NOT NULL,
	"identified_date" text,
	"due_date" text,
	"notes" text,
	"document_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"detail" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_by" text NOT NULL,
	"closed_by" text,
	"closed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "change_line_items" (
	"id" text PRIMARY KEY NOT NULL,
	"company_id" text NOT NULL,
	"project_id" text NOT NULL,
	"parent_type" text NOT NULL,
	"parent_id" text NOT NULL,
	"change_event_id" text,
	"line_number" text,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"cost_code_id" text,
	"cost_code" text,
	"cost_type" text,
	"budget_line_item_id" text,
	"description" text NOT NULL,
	"unit" text,
	"quantity" double precision,
	"unit_rate" double precision,
	"cost_amount" double precision DEFAULT 0 NOT NULL,
	"revenue_amount" double precision DEFAULT 0 NOT NULL,
	"markup_kind" text,
	"markup_percent" double precision,
	"markup_amount" double precision DEFAULT 0 NOT NULL,
	"tax_percent" double precision,
	"tax_amount" double precision DEFAULT 0 NOT NULL,
	"vendor_id" text,
	"commitment_sov_line_id" text,
	"prime_contract_sov_line_id" text,
	"notes" text,
	"detail" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_by" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "change_order_packages" (
	"id" text PRIMARY KEY NOT NULL,
	"company_id" text NOT NULL,
	"project_id" text NOT NULL,
	"kind" text NOT NULL,
	"number" integer NOT NULL,
	"reference" text NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"status" text DEFAULT 'draft' NOT NULL,
	"prime_contract_id" text,
	"commitment_id" text,
	"change_event_id" text,
	"member_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"amount" double precision DEFAULT 0 NOT NULL,
	"schedule_impact_days" integer DEFAULT 0 NOT NULL,
	"prime_contract_change_id" text,
	"commitment_change_id" text,
	"budget_change_id" text,
	"executed_at" timestamp with time zone,
	"executed_by" text,
	"signed_date" text,
	"due_date" text,
	"document_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"detail" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_by" text NOT NULL,
	"submitted_by" text,
	"submitted_at" timestamp with time zone,
	"approved_by" text,
	"approved_at" timestamp with time zone,
	"rejected_by" text,
	"rejected_at" timestamp with time zone,
	"rejection_reason" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "change_order_requests" (
	"id" text PRIMARY KEY NOT NULL,
	"company_id" text NOT NULL,
	"project_id" text NOT NULL,
	"prime_contract_id" text NOT NULL,
	"change_event_id" text,
	"number" integer NOT NULL,
	"reference" text NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"reason" text,
	"status" text DEFAULT 'draft' NOT NULL,
	"pco_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"markups" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"subtotal" double precision DEFAULT 0 NOT NULL,
	"markup_total" double precision DEFAULT 0 NOT NULL,
	"tax_total" double precision DEFAULT 0 NOT NULL,
	"amount" double precision DEFAULT 0 NOT NULL,
	"approved_amount" double precision DEFAULT 0 NOT NULL,
	"schedule_impact_days" integer DEFAULT 0 NOT NULL,
	"schedule_impact_approved_days" integer DEFAULT 0 NOT NULL,
	"submitted_date" text,
	"due_date" text,
	"owner_response_date" text,
	"change_order_package_id" text,
	"negotiation_notes" text,
	"document_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"detail" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_by" text NOT NULL,
	"submitted_by" text,
	"submitted_at" timestamp with time zone,
	"approved_by" text,
	"approved_at" timestamp with time zone,
	"rejected_by" text,
	"rejected_at" timestamp with time zone,
	"rejection_reason" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "change_quote_requests" (
	"id" text PRIMARY KEY NOT NULL,
	"company_id" text NOT NULL,
	"project_id" text NOT NULL,
	"change_event_id" text,
	"potential_change_order_id" text,
	"commitment_id" text,
	"vendor_id" text,
	"vendor_contact_id" text,
	"number" integer NOT NULL,
	"reference" text NOT NULL,
	"title" text NOT NULL,
	"scope_description" text,
	"status" text DEFAULT 'draft' NOT NULL,
	"due_date" text,
	"sent_at" timestamp with time zone,
	"sent_by" text,
	"viewed_at" timestamp with time zone,
	"responded_at" timestamp with time zone,
	"quoted_amount" double precision,
	"quoted_schedule_impact_days" integer,
	"quote_notes" text,
	"quote_valid_until" text,
	"quote_document_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"accepted_at" timestamp with time zone,
	"accepted_by" text,
	"declined_at" timestamp with time zone,
	"decline_reason" text,
	"detail" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_by" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "commitment_changes" (
	"id" text PRIMARY KEY NOT NULL,
	"company_id" text NOT NULL,
	"project_id" text NOT NULL,
	"commitment_id" text NOT NULL,
	"number" integer NOT NULL,
	"reference" text NOT NULL,
	"change_order_package_id" text,
	"potential_change_order_id" text,
	"title" text NOT NULL,
	"description" text,
	"reason" text,
	"status" text DEFAULT 'draft' NOT NULL,
	"amount" double precision DEFAULT 0 NOT NULL,
	"schedule_impact_days" integer DEFAULT 0 NOT NULL,
	"lines" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"revised_commitment_sum" double precision DEFAULT 0 NOT NULL,
	"requested_date" text,
	"due_date" text,
	"executed_date" text,
	"signed_change_order_received_date" text,
	"detail" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_by" text NOT NULL,
	"submitted_by" text,
	"submitted_at" timestamp with time zone,
	"approved_by" text,
	"approved_at" timestamp with time zone,
	"rejected_by" text,
	"rejected_at" timestamp with time zone,
	"rejection_reason" text,
	"executed_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "commitment_payments" (
	"id" text PRIMARY KEY NOT NULL,
	"company_id" text NOT NULL,
	"project_id" text NOT NULL,
	"commitment_id" text NOT NULL,
	"invoice_id" text,
	"vendor_id" text,
	"number" integer NOT NULL,
	"reference" text NOT NULL,
	"method" text DEFAULT 'check' NOT NULL,
	"status" text DEFAULT 'scheduled' NOT NULL,
	"amount" double precision DEFAULT 0 NOT NULL,
	"retainage_released_amount" double precision DEFAULT 0 NOT NULL,
	"discount_taken" double precision DEFAULT 0 NOT NULL,
	"currency" text DEFAULT 'USD' NOT NULL,
	"payment_date" text,
	"cleared_date" text,
	"check_number" text,
	"transaction_reference" text,
	"bank_account_ref" text,
	"joint_payees" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"hold_reason" text,
	"lien_waiver_id" text,
	"notes" text,
	"detail" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_by" text NOT NULL,
	"approved_by" text,
	"approved_at" timestamp with time zone,
	"issued_by" text,
	"issued_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "commitment_sov_lines" (
	"id" text PRIMARY KEY NOT NULL,
	"company_id" text NOT NULL,
	"project_id" text NOT NULL,
	"commitment_id" text NOT NULL,
	"line_number" text NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"cost_code_id" text,
	"cost_code" text,
	"cost_type" text,
	"budget_line_item_id" text,
	"description" text NOT NULL,
	"billing_method" text DEFAULT 'percent_complete' NOT NULL,
	"unit" text,
	"quantity" double precision,
	"unit_rate" double precision,
	"scheduled_value" double precision DEFAULT 0 NOT NULL,
	"change_order_value" double precision DEFAULT 0 NOT NULL,
	"revised_scheduled_value" double precision DEFAULT 0 NOT NULL,
	"previous_billed" double precision DEFAULT 0 NOT NULL,
	"previous_stored_materials" double precision DEFAULT 0 NOT NULL,
	"this_period_work" double precision DEFAULT 0 NOT NULL,
	"this_period_stored_materials" double precision DEFAULT 0 NOT NULL,
	"materials_presently_stored" double precision DEFAULT 0 NOT NULL,
	"total_completed_and_stored" double precision DEFAULT 0 NOT NULL,
	"percent_complete" double precision DEFAULT 0 NOT NULL,
	"balance_to_finish" double precision DEFAULT 0 NOT NULL,
	"retainage_percent" double precision DEFAULT 0 NOT NULL,
	"retainage_held" double precision DEFAULT 0 NOT NULL,
	"retainage_released" double precision DEFAULT 0 NOT NULL,
	"is_change_order_line" integer DEFAULT 0 NOT NULL,
	"change_order_package_id" text,
	"taxable" integer DEFAULT 0 NOT NULL,
	"tax_code" text,
	"tax_percent" double precision,
	"notes" text,
	"detail" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "commitments" (
	"id" text PRIMARY KEY NOT NULL,
	"company_id" text NOT NULL,
	"project_id" text NOT NULL,
	"kind" text DEFAULT 'subcontract' NOT NULL,
	"number" integer NOT NULL,
	"reference" text NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"scope_of_work" text,
	"vendor_id" text,
	"vendor_contact_id" text,
	"contract_id" text,
	"prime_contract_id" text,
	"pricing_type" text DEFAULT 'lump_sum' NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"executed" integer DEFAULT 0 NOT NULL,
	"currency" text DEFAULT 'USD' NOT NULL,
	"original_commitment_sum" double precision DEFAULT 0 NOT NULL,
	"approved_change_sum" double precision DEFAULT 0 NOT NULL,
	"pending_change_sum" double precision DEFAULT 0 NOT NULL,
	"draft_change_sum" double precision DEFAULT 0 NOT NULL,
	"revised_commitment_sum" double precision DEFAULT 0 NOT NULL,
	"total_invoiced" double precision DEFAULT 0 NOT NULL,
	"total_paid" double precision DEFAULT 0 NOT NULL,
	"default_retainage_percent" double precision DEFAULT 0 NOT NULL,
	"retainage_held" double precision DEFAULT 0 NOT NULL,
	"retainage_released" double precision DEFAULT 0 NOT NULL,
	"balance_to_finish" double precision DEFAULT 0 NOT NULL,
	"totals_calculated_at" timestamp with time zone,
	"contract_date" text,
	"start_date" text,
	"estimated_completion_date" text,
	"actual_completion_date" text,
	"signed_contract_received_date" text,
	"execution_date" text,
	"termination_date" text,
	"payment_terms_days" integer,
	"requires_lien_waiver" integer DEFAULT 1 NOT NULL,
	"payment_hold" integer DEFAULT 0 NOT NULL,
	"compliance_hold_reason" text,
	"compliance_detail" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"ship_to" text,
	"ship_via" text,
	"delivery_date" text,
	"taxable" integer DEFAULT 0 NOT NULL,
	"tax_percent" double precision,
	"tax_amount" double precision,
	"inclusions" text,
	"exclusions" text,
	"document_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"detail" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_by" text NOT NULL,
	"approved_by" text,
	"approved_at" timestamp with time zone,
	"executed_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "invoice_line_items" (
	"id" text PRIMARY KEY NOT NULL,
	"company_id" text NOT NULL,
	"project_id" text NOT NULL,
	"invoice_id" text NOT NULL,
	"line_number" text NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"prime_contract_sov_line_id" text,
	"commitment_sov_line_id" text,
	"cost_code_id" text,
	"cost_code" text,
	"cost_type" text,
	"budget_line_item_id" text,
	"description" text NOT NULL,
	"source" text DEFAULT 'contract_sov' NOT NULL,
	"billing_method" text DEFAULT 'percent_complete' NOT NULL,
	"unit" text,
	"quantity" double precision,
	"unit_rate" double precision,
	"scheduled_value" double precision DEFAULT 0 NOT NULL,
	"previous_billed" double precision DEFAULT 0 NOT NULL,
	"previous_stored_materials" double precision DEFAULT 0 NOT NULL,
	"this_period_work" double precision DEFAULT 0 NOT NULL,
	"this_period_stored_materials" double precision DEFAULT 0 NOT NULL,
	"materials_presently_stored" double precision DEFAULT 0 NOT NULL,
	"total_completed_and_stored" double precision DEFAULT 0 NOT NULL,
	"percent_complete" double precision DEFAULT 0 NOT NULL,
	"balance_to_finish" double precision DEFAULT 0 NOT NULL,
	"retainage_percent" double precision DEFAULT 0 NOT NULL,
	"retainage_this_period" double precision DEFAULT 0 NOT NULL,
	"retainage_held_to_date" double precision DEFAULT 0 NOT NULL,
	"retainage_released" double precision DEFAULT 0 NOT NULL,
	"amount" double precision DEFAULT 0 NOT NULL,
	"tax_percent" double precision,
	"tax_amount" double precision DEFAULT 0 NOT NULL,
	"change_order_package_id" text,
	"notes" text,
	"detail" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "invoices" (
	"id" text PRIMARY KEY NOT NULL,
	"company_id" text NOT NULL,
	"project_id" text NOT NULL,
	"kind" text NOT NULL,
	"number" integer NOT NULL,
	"reference" text NOT NULL,
	"title" text,
	"status" text DEFAULT 'draft' NOT NULL,
	"prime_contract_id" text,
	"commitment_id" text,
	"vendor_id" text,
	"billing_period_id" text,
	"invoice_number" text,
	"currency" text DEFAULT 'USD' NOT NULL,
	"billing_date" text,
	"period_start" text,
	"period_end" text,
	"due_date" text,
	"received_date" text,
	"original_contract_sum" double precision DEFAULT 0 NOT NULL,
	"net_change_orders" double precision DEFAULT 0 NOT NULL,
	"revised_contract_sum" double precision DEFAULT 0 NOT NULL,
	"completed_to_date" double precision DEFAULT 0 NOT NULL,
	"stored_materials" double precision DEFAULT 0 NOT NULL,
	"total_completed_and_stored" double precision DEFAULT 0 NOT NULL,
	"retainage_percent_work" double precision DEFAULT 0 NOT NULL,
	"retainage_work" double precision DEFAULT 0 NOT NULL,
	"retainage_percent_materials" double precision DEFAULT 0 NOT NULL,
	"retainage_materials" double precision DEFAULT 0 NOT NULL,
	"total_retainage" double precision DEFAULT 0 NOT NULL,
	"retainage_released" double precision DEFAULT 0 NOT NULL,
	"total_earned_less_retainage" double precision DEFAULT 0 NOT NULL,
	"previous_payments_amount" double precision DEFAULT 0 NOT NULL,
	"current_payment_due" double precision DEFAULT 0 NOT NULL,
	"balance_to_finish_plus_retainage" double precision DEFAULT 0 NOT NULL,
	"subtotal" double precision DEFAULT 0 NOT NULL,
	"tax_amount" double precision DEFAULT 0 NOT NULL,
	"total" double precision DEFAULT 0 NOT NULL,
	"amount_paid" double precision DEFAULT 0 NOT NULL,
	"paid_date" text,
	"review_notes" text,
	"rejection_reason" text,
	"requires_lien_waiver" integer DEFAULT 0 NOT NULL,
	"lien_waiver_status" text,
	"document_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"detail" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_by" text NOT NULL,
	"submitted_by" text,
	"submitted_at" timestamp with time zone,
	"reviewed_by" text,
	"reviewed_at" timestamp with time zone,
	"approved_by" text,
	"approved_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "lien_waivers" (
	"id" text PRIMARY KEY NOT NULL,
	"company_id" text NOT NULL,
	"project_id" text NOT NULL,
	"number" integer NOT NULL,
	"reference" text NOT NULL,
	"waiver_type" text NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"commitment_id" text,
	"invoice_id" text,
	"payment_id" text,
	"billing_period_id" text,
	"vendor_id" text,
	"vendor_contact_id" text,
	"tier" integer DEFAULT 1 NOT NULL,
	"claimant_name" text,
	"claimant_address" text,
	"amount" double precision DEFAULT 0 NOT NULL,
	"currency" text DEFAULT 'USD' NOT NULL,
	"through_date" text,
	"exceptions_noted" text,
	"jurisdiction" text,
	"statutory_form" text,
	"requested_by" text,
	"requested_at" timestamp with time zone,
	"sent_at" timestamp with time zone,
	"signed_at" timestamp with time zone,
	"signed_by_name" text,
	"signature_method" text,
	"signature_reference" text,
	"received_at" timestamp with time zone,
	"received_by" text,
	"verified_at" timestamp with time zone,
	"verified_by" text,
	"rejection_reason" text,
	"document_id" text,
	"notes" text,
	"detail" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_by" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "payment_applications" (
	"id" text PRIMARY KEY NOT NULL,
	"company_id" text NOT NULL,
	"project_id" text NOT NULL,
	"prime_contract_id" text NOT NULL,
	"invoice_id" text,
	"billing_period_id" text,
	"number" integer NOT NULL,
	"reference" text NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"application_date" text,
	"period_to" text,
	"currency" text DEFAULT 'USD' NOT NULL,
	"original_contract_sum" double precision DEFAULT 0 NOT NULL,
	"net_change_orders" double precision DEFAULT 0 NOT NULL,
	"contract_sum_to_date" double precision DEFAULT 0 NOT NULL,
	"total_completed_and_stored" double precision DEFAULT 0 NOT NULL,
	"total_retainage" double precision DEFAULT 0 NOT NULL,
	"total_earned_less_retainage" double precision DEFAULT 0 NOT NULL,
	"less_previous_certificates" double precision DEFAULT 0 NOT NULL,
	"current_payment_due" double precision DEFAULT 0 NOT NULL,
	"balance_to_finish_plus_retainage" double precision DEFAULT 0 NOT NULL,
	"certified_by_contractor_name" text,
	"contractor_certified_at" timestamp with time zone,
	"notary_reference" text,
	"architect_vendor_id" text,
	"certified_amount" double precision,
	"certification_notes" text,
	"certified_by" text,
	"certified_at" timestamp with time zone,
	"paid_amount" double precision DEFAULT 0 NOT NULL,
	"paid_at" timestamp with time zone,
	"payment_reference" text,
	"document_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"detail" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_by" text NOT NULL,
	"submitted_by" text,
	"submitted_at" timestamp with time zone,
	"rejected_by" text,
	"rejected_at" timestamp with time zone,
	"rejection_reason" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "potential_change_orders" (
	"id" text PRIMARY KEY NOT NULL,
	"company_id" text NOT NULL,
	"project_id" text NOT NULL,
	"change_event_id" text,
	"number" integer NOT NULL,
	"reference" text NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"status" text DEFAULT 'draft' NOT NULL,
	"reason" text,
	"scope" text DEFAULT 'tbd' NOT NULL,
	"commitment_id" text,
	"vendor_id" text,
	"prime_contract_id" text,
	"change_order_request_id" text,
	"change_order_package_id" text,
	"estimated_amount" double precision DEFAULT 0 NOT NULL,
	"quoted_amount" double precision DEFAULT 0 NOT NULL,
	"amount" double precision DEFAULT 0 NOT NULL,
	"schedule_impact_days" integer DEFAULT 0 NOT NULL,
	"no_charge" integer DEFAULT 0 NOT NULL,
	"due_date" text,
	"detail" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_by" text NOT NULL,
	"submitted_by" text,
	"submitted_at" timestamp with time zone,
	"approved_by" text,
	"approved_at" timestamp with time zone,
	"rejected_by" text,
	"rejected_at" timestamp with time zone,
	"rejection_reason" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "prime_contract_changes" (
	"id" text PRIMARY KEY NOT NULL,
	"company_id" text NOT NULL,
	"project_id" text NOT NULL,
	"prime_contract_id" text NOT NULL,
	"number" integer NOT NULL,
	"reference" text NOT NULL,
	"change_order_package_id" text,
	"title" text NOT NULL,
	"description" text,
	"reason" text,
	"status" text DEFAULT 'draft' NOT NULL,
	"amount" double precision DEFAULT 0 NOT NULL,
	"schedule_impact_days" integer DEFAULT 0 NOT NULL,
	"lines" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"revised_contract_sum" double precision DEFAULT 0 NOT NULL,
	"requested_date" text,
	"due_date" text,
	"executed_date" text,
	"signed_change_order_received_date" text,
	"detail" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_by" text NOT NULL,
	"submitted_by" text,
	"submitted_at" timestamp with time zone,
	"approved_by" text,
	"approved_at" timestamp with time zone,
	"rejected_by" text,
	"rejected_at" timestamp with time zone,
	"rejection_reason" text,
	"executed_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "prime_contract_sov_lines" (
	"id" text PRIMARY KEY NOT NULL,
	"company_id" text NOT NULL,
	"project_id" text NOT NULL,
	"prime_contract_id" text NOT NULL,
	"line_number" text NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"cost_code_id" text,
	"cost_code" text,
	"cost_type" text,
	"budget_line_item_id" text,
	"description" text NOT NULL,
	"billing_method" text DEFAULT 'percent_complete' NOT NULL,
	"unit" text,
	"quantity" double precision,
	"unit_rate" double precision,
	"scheduled_value" double precision DEFAULT 0 NOT NULL,
	"change_order_value" double precision DEFAULT 0 NOT NULL,
	"revised_scheduled_value" double precision DEFAULT 0 NOT NULL,
	"previous_billed" double precision DEFAULT 0 NOT NULL,
	"previous_stored_materials" double precision DEFAULT 0 NOT NULL,
	"this_period_work" double precision DEFAULT 0 NOT NULL,
	"this_period_stored_materials" double precision DEFAULT 0 NOT NULL,
	"materials_presently_stored" double precision DEFAULT 0 NOT NULL,
	"total_completed_and_stored" double precision DEFAULT 0 NOT NULL,
	"percent_complete" double precision DEFAULT 0 NOT NULL,
	"balance_to_finish" double precision DEFAULT 0 NOT NULL,
	"retainage_percent" double precision DEFAULT 0 NOT NULL,
	"retainage_held" double precision DEFAULT 0 NOT NULL,
	"retainage_released" double precision DEFAULT 0 NOT NULL,
	"is_change_order_line" integer DEFAULT 0 NOT NULL,
	"change_order_package_id" text,
	"notes" text,
	"detail" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "prime_contracts" (
	"id" text PRIMARY KEY NOT NULL,
	"company_id" text NOT NULL,
	"project_id" text NOT NULL,
	"number" integer NOT NULL,
	"reference" text NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"scope_of_work" text,
	"owner_vendor_id" text,
	"owner_contact_id" text,
	"contractor_vendor_id" text,
	"architect_vendor_id" text,
	"contract_id" text,
	"pricing_type" text DEFAULT 'lump_sum' NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"executed" integer DEFAULT 0 NOT NULL,
	"currency" text DEFAULT 'USD' NOT NULL,
	"original_contract_sum" double precision DEFAULT 0 NOT NULL,
	"approved_change_sum" double precision DEFAULT 0 NOT NULL,
	"pending_change_sum" double precision DEFAULT 0 NOT NULL,
	"draft_change_sum" double precision DEFAULT 0 NOT NULL,
	"revised_contract_sum" double precision DEFAULT 0 NOT NULL,
	"total_billed" double precision DEFAULT 0 NOT NULL,
	"total_paid" double precision DEFAULT 0 NOT NULL,
	"default_retainage_percent" double precision DEFAULT 0 NOT NULL,
	"retainage_held" double precision DEFAULT 0 NOT NULL,
	"retainage_released" double precision DEFAULT 0 NOT NULL,
	"balance_to_finish" double precision DEFAULT 0 NOT NULL,
	"totals_calculated_at" timestamp with time zone,
	"contract_date" text,
	"start_date" text,
	"substantial_completion_date" text,
	"actual_completion_date" text,
	"signed_contract_received_date" text,
	"execution_date" text,
	"termination_date" text,
	"payment_terms_days" integer,
	"inclusions" text,
	"exclusions" text,
	"document_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"detail" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_by" text NOT NULL,
	"approved_by" text,
	"approved_at" timestamp with time zone,
	"executed_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "retainage_releases" (
	"id" text PRIMARY KEY NOT NULL,
	"company_id" text NOT NULL,
	"project_id" text NOT NULL,
	"number" integer NOT NULL,
	"reference" text NOT NULL,
	"scope" text NOT NULL,
	"prime_contract_id" text,
	"commitment_id" text,
	"vendor_id" text,
	"invoice_id" text,
	"billing_period_id" text,
	"status" text DEFAULT 'draft' NOT NULL,
	"basis" text DEFAULT 'percent_work_completed' NOT NULL,
	"retainage_held_before" double precision DEFAULT 0 NOT NULL,
	"amount" double precision DEFAULT 0 NOT NULL,
	"retainage_held_after" double precision DEFAULT 0 NOT NULL,
	"new_retainage_percent" double precision,
	"lines" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"effective_date" text,
	"release_date" text,
	"reason" text,
	"conditions" text,
	"requires_lien_waiver" integer DEFAULT 0 NOT NULL,
	"lien_waiver_id" text,
	"detail" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_by" text NOT NULL,
	"requested_by" text,
	"requested_at" timestamp with time zone,
	"approved_by" text,
	"approved_at" timestamp with time zone,
	"rejected_by" text,
	"rejected_at" timestamp with time zone,
	"rejection_reason" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "billing_periods_uq" ON "billing_periods" USING btree ("project_id","number");--> statement-breakpoint
CREATE INDEX "billing_periods_project_idx" ON "billing_periods" USING btree ("project_id","status");--> statement-breakpoint
CREATE INDEX "billing_periods_date_idx" ON "billing_periods" USING btree ("project_id","billing_date");--> statement-breakpoint
CREATE UNIQUE INDEX "budget_changes_uq" ON "budget_changes" USING btree ("budget_id","number");--> statement-breakpoint
CREATE INDEX "budget_changes_project_idx" ON "budget_changes" USING btree ("project_id","status");--> statement-breakpoint
CREATE INDEX "budget_changes_source_idx" ON "budget_changes" USING btree ("source_type","source_id");--> statement-breakpoint
CREATE UNIQUE INDEX "budget_forecasts_uq" ON "budget_forecasts" USING btree ("budget_id","number");--> statement-breakpoint
CREATE INDEX "budget_forecasts_line_idx" ON "budget_forecasts" USING btree ("line_item_id","as_of_date");--> statement-breakpoint
CREATE INDEX "budget_forecasts_project_idx" ON "budget_forecasts" USING btree ("project_id","as_of_date");--> statement-breakpoint
CREATE UNIQUE INDEX "budget_line_items_uq" ON "budget_line_items" USING btree ("budget_id","cost_code","cost_type");--> statement-breakpoint
CREATE INDEX "budget_line_items_budget_idx" ON "budget_line_items" USING btree ("budget_id","sort_order");--> statement-breakpoint
CREATE INDEX "budget_line_items_project_idx" ON "budget_line_items" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "budget_line_items_cost_code_idx" ON "budget_line_items" USING btree ("cost_code_id");--> statement-breakpoint
CREATE UNIQUE INDEX "budget_snapshots_uq" ON "budget_snapshots" USING btree ("budget_id","number");--> statement-breakpoint
CREATE INDEX "budget_snapshots_project_idx" ON "budget_snapshots" USING btree ("project_id","as_of_date");--> statement-breakpoint
CREATE UNIQUE INDEX "budgets_uq" ON "budgets" USING btree ("project_id","number");--> statement-breakpoint
CREATE INDEX "budgets_project_idx" ON "budgets" USING btree ("project_id","status");--> statement-breakpoint
CREATE INDEX "budgets_company_idx" ON "budgets" USING btree ("company_id");--> statement-breakpoint
CREATE UNIQUE INDEX "change_events_uq" ON "change_events" USING btree ("project_id","number");--> statement-breakpoint
CREATE INDEX "change_events_project_idx" ON "change_events" USING btree ("project_id","status");--> statement-breakpoint
CREATE INDEX "change_events_origin_idx" ON "change_events" USING btree ("origin_type","origin_id");--> statement-breakpoint
CREATE INDEX "change_events_contract_idx" ON "change_events" USING btree ("prime_contract_id");--> statement-breakpoint
CREATE INDEX "change_line_items_parent_idx" ON "change_line_items" USING btree ("parent_type","parent_id","sort_order");--> statement-breakpoint
CREATE INDEX "change_line_items_event_idx" ON "change_line_items" USING btree ("change_event_id");--> statement-breakpoint
CREATE INDEX "change_line_items_budget_idx" ON "change_line_items" USING btree ("budget_line_item_id");--> statement-breakpoint
CREATE INDEX "change_line_items_project_idx" ON "change_line_items" USING btree ("project_id");--> statement-breakpoint
CREATE UNIQUE INDEX "change_order_packages_uq" ON "change_order_packages" USING btree ("project_id","kind","number");--> statement-breakpoint
CREATE INDEX "change_order_packages_prime_idx" ON "change_order_packages" USING btree ("prime_contract_id","status");--> statement-breakpoint
CREATE INDEX "change_order_packages_commitment_idx" ON "change_order_packages" USING btree ("commitment_id","status");--> statement-breakpoint
CREATE INDEX "change_order_packages_event_idx" ON "change_order_packages" USING btree ("change_event_id");--> statement-breakpoint
CREATE UNIQUE INDEX "change_order_requests_uq" ON "change_order_requests" USING btree ("project_id","number");--> statement-breakpoint
CREATE INDEX "change_order_requests_contract_idx" ON "change_order_requests" USING btree ("prime_contract_id","status");--> statement-breakpoint
CREATE INDEX "change_order_requests_event_idx" ON "change_order_requests" USING btree ("change_event_id");--> statement-breakpoint
CREATE INDEX "change_order_requests_project_idx" ON "change_order_requests" USING btree ("project_id","status");--> statement-breakpoint
CREATE UNIQUE INDEX "change_quote_requests_uq" ON "change_quote_requests" USING btree ("project_id","number");--> statement-breakpoint
CREATE INDEX "change_quote_requests_pco_idx" ON "change_quote_requests" USING btree ("potential_change_order_id");--> statement-breakpoint
CREATE INDEX "change_quote_requests_vendor_idx" ON "change_quote_requests" USING btree ("vendor_id","status");--> statement-breakpoint
CREATE INDEX "change_quote_requests_project_idx" ON "change_quote_requests" USING btree ("project_id","status");--> statement-breakpoint
CREATE UNIQUE INDEX "commitment_changes_uq" ON "commitment_changes" USING btree ("commitment_id","number");--> statement-breakpoint
CREATE INDEX "commitment_changes_project_idx" ON "commitment_changes" USING btree ("project_id","status");--> statement-breakpoint
CREATE INDEX "commitment_changes_package_idx" ON "commitment_changes" USING btree ("change_order_package_id");--> statement-breakpoint
CREATE UNIQUE INDEX "commitment_payments_uq" ON "commitment_payments" USING btree ("commitment_id","number");--> statement-breakpoint
CREATE INDEX "commitment_payments_project_idx" ON "commitment_payments" USING btree ("project_id","status");--> statement-breakpoint
CREATE INDEX "commitment_payments_invoice_idx" ON "commitment_payments" USING btree ("invoice_id");--> statement-breakpoint
CREATE INDEX "commitment_payments_vendor_idx" ON "commitment_payments" USING btree ("vendor_id");--> statement-breakpoint
CREATE UNIQUE INDEX "commitment_sov_lines_uq" ON "commitment_sov_lines" USING btree ("commitment_id","line_number");--> statement-breakpoint
CREATE INDEX "commitment_sov_lines_commitment_idx" ON "commitment_sov_lines" USING btree ("commitment_id","sort_order");--> statement-breakpoint
CREATE INDEX "commitment_sov_lines_budget_idx" ON "commitment_sov_lines" USING btree ("budget_line_item_id");--> statement-breakpoint
CREATE INDEX "commitment_sov_lines_project_idx" ON "commitment_sov_lines" USING btree ("project_id");--> statement-breakpoint
CREATE UNIQUE INDEX "commitments_uq" ON "commitments" USING btree ("project_id","number");--> statement-breakpoint
CREATE INDEX "commitments_project_idx" ON "commitments" USING btree ("project_id","kind","status");--> statement-breakpoint
CREATE INDEX "commitments_vendor_idx" ON "commitments" USING btree ("vendor_id");--> statement-breakpoint
CREATE INDEX "commitments_company_idx" ON "commitments" USING btree ("company_id");--> statement-breakpoint
CREATE UNIQUE INDEX "invoice_line_items_uq" ON "invoice_line_items" USING btree ("invoice_id","line_number");--> statement-breakpoint
CREATE INDEX "invoice_line_items_invoice_idx" ON "invoice_line_items" USING btree ("invoice_id","sort_order");--> statement-breakpoint
CREATE INDEX "invoice_line_items_prime_sov_idx" ON "invoice_line_items" USING btree ("prime_contract_sov_line_id");--> statement-breakpoint
CREATE INDEX "invoice_line_items_commitment_sov_idx" ON "invoice_line_items" USING btree ("commitment_sov_line_id");--> statement-breakpoint
CREATE INDEX "invoice_line_items_budget_idx" ON "invoice_line_items" USING btree ("budget_line_item_id");--> statement-breakpoint
CREATE UNIQUE INDEX "invoices_uq" ON "invoices" USING btree ("project_id","kind","number");--> statement-breakpoint
CREATE INDEX "invoices_project_idx" ON "invoices" USING btree ("project_id","status");--> statement-breakpoint
CREATE INDEX "invoices_commitment_idx" ON "invoices" USING btree ("commitment_id","status");--> statement-breakpoint
CREATE INDEX "invoices_prime_idx" ON "invoices" USING btree ("prime_contract_id","status");--> statement-breakpoint
CREATE INDEX "invoices_period_idx" ON "invoices" USING btree ("billing_period_id");--> statement-breakpoint
CREATE INDEX "invoices_vendor_idx" ON "invoices" USING btree ("vendor_id");--> statement-breakpoint
CREATE UNIQUE INDEX "lien_waivers_uq" ON "lien_waivers" USING btree ("project_id","number");--> statement-breakpoint
CREATE INDEX "lien_waivers_commitment_idx" ON "lien_waivers" USING btree ("commitment_id","status");--> statement-breakpoint
CREATE INDEX "lien_waivers_invoice_idx" ON "lien_waivers" USING btree ("invoice_id");--> statement-breakpoint
CREATE INDEX "lien_waivers_vendor_idx" ON "lien_waivers" USING btree ("vendor_id","status");--> statement-breakpoint
CREATE INDEX "lien_waivers_through_idx" ON "lien_waivers" USING btree ("project_id","through_date");--> statement-breakpoint
CREATE UNIQUE INDEX "payment_applications_uq" ON "payment_applications" USING btree ("project_id","number");--> statement-breakpoint
CREATE INDEX "payment_applications_contract_idx" ON "payment_applications" USING btree ("prime_contract_id","status");--> statement-breakpoint
CREATE INDEX "payment_applications_invoice_idx" ON "payment_applications" USING btree ("invoice_id");--> statement-breakpoint
CREATE INDEX "payment_applications_period_idx" ON "payment_applications" USING btree ("billing_period_id");--> statement-breakpoint
CREATE UNIQUE INDEX "potential_change_orders_uq" ON "potential_change_orders" USING btree ("project_id","number");--> statement-breakpoint
CREATE INDEX "potential_change_orders_event_idx" ON "potential_change_orders" USING btree ("change_event_id");--> statement-breakpoint
CREATE INDEX "potential_change_orders_commitment_idx" ON "potential_change_orders" USING btree ("commitment_id");--> statement-breakpoint
CREATE INDEX "potential_change_orders_project_idx" ON "potential_change_orders" USING btree ("project_id","status");--> statement-breakpoint
CREATE UNIQUE INDEX "prime_contract_changes_uq" ON "prime_contract_changes" USING btree ("prime_contract_id","number");--> statement-breakpoint
CREATE INDEX "prime_contract_changes_project_idx" ON "prime_contract_changes" USING btree ("project_id","status");--> statement-breakpoint
CREATE INDEX "prime_contract_changes_package_idx" ON "prime_contract_changes" USING btree ("change_order_package_id");--> statement-breakpoint
CREATE UNIQUE INDEX "prime_contract_sov_lines_uq" ON "prime_contract_sov_lines" USING btree ("prime_contract_id","line_number");--> statement-breakpoint
CREATE INDEX "prime_contract_sov_lines_contract_idx" ON "prime_contract_sov_lines" USING btree ("prime_contract_id","sort_order");--> statement-breakpoint
CREATE INDEX "prime_contract_sov_lines_budget_idx" ON "prime_contract_sov_lines" USING btree ("budget_line_item_id");--> statement-breakpoint
CREATE INDEX "prime_contract_sov_lines_project_idx" ON "prime_contract_sov_lines" USING btree ("project_id");--> statement-breakpoint
CREATE UNIQUE INDEX "prime_contracts_uq" ON "prime_contracts" USING btree ("project_id","number");--> statement-breakpoint
CREATE INDEX "prime_contracts_project_idx" ON "prime_contracts" USING btree ("project_id","status");--> statement-breakpoint
CREATE INDEX "prime_contracts_company_idx" ON "prime_contracts" USING btree ("company_id");--> statement-breakpoint
CREATE UNIQUE INDEX "retainage_releases_uq" ON "retainage_releases" USING btree ("project_id","number");--> statement-breakpoint
CREATE INDEX "retainage_releases_commitment_idx" ON "retainage_releases" USING btree ("commitment_id","status");--> statement-breakpoint
CREATE INDEX "retainage_releases_prime_idx" ON "retainage_releases" USING btree ("prime_contract_id","status");--> statement-breakpoint
CREATE INDEX "retainage_releases_project_idx" ON "retainage_releases" USING btree ("project_id","status");