import { describe, expect, it } from "vitest";
import { buildOpenApiDocument, parseRouteTree, tagForPath, toOpenApiPath } from "./openapi.js";

/**
 * The document is generated by parsing Fastify's pretty-printed route tree —
 * the only enumeration Fastify exposes publicly. A parser nobody tests is a
 * parser that returns an empty document the day the format shifts and nobody
 * notices, so the exact tree shapes Fastify produces are fixtures here.
 */

const TREE = `├── /api/v1/analytics/datasets (GET, HEAD)
├── /api/v1/analytics/reports (GET, HEAD, POST)
│   ├── /preview (POST)
│   └── /:reportId (DELETE, GET, HEAD, PATCH)
│       └── /schedules/:scheduleId (DELETE, PATCH)
├── /api/v1/integrations/webhooks (GET, HEAD, POST)
└── /api/v1/projects/:projectId/analytics/forecast (GET, HEAD, POST)
`;

describe("parseRouteTree", () => {
  it("reconstructs full paths from the indented tree", () => {
    const routes = parseRouteTree(TREE);
    const paths = routes.map((r) => r.path);
    expect(paths).toContain("/api/v1/analytics/datasets");
    expect(paths).toContain("/api/v1/analytics/reports");
    expect(paths).toContain("/api/v1/analytics/reports/preview");
    expect(paths).toContain("/api/v1/analytics/reports/:reportId");
    expect(paths).toContain("/api/v1/analytics/reports/:reportId/schedules/:scheduleId");
    expect(paths).toContain("/api/v1/projects/:projectId/analytics/forecast");
  });

  it("drops HEAD and OPTIONS, which are transport, not API surface", () => {
    const routes = parseRouteTree(TREE);
    const datasets = routes.find((r) => r.path === "/api/v1/analytics/datasets")!;
    expect(datasets.methods).toEqual(["GET"]);
    const reports = routes.find((r) => r.path === "/api/v1/analytics/reports")!;
    expect(reports.methods).toEqual(["GET", "POST"]);
  });

  it("returns nothing for an empty tree rather than throwing", () => {
    expect(parseRouteTree("")).toEqual([]);
    expect(parseRouteTree("\n\n")).toEqual([]);
  });

  it("handles a node with no methods (a pure branch)", () => {
    const routes = parseRouteTree(`├── /api/v1/a
│   └── /b (GET)
`);
    expect(routes).toEqual([{ path: "/api/v1/a/b", methods: ["GET"] }]);
  });
});

describe("path conversion", () => {
  it("rewrites :params as {params} and lists them", () => {
    expect(toOpenApiPath("/api/v1/projects/:projectId/rfis/:rfiId")).toEqual({
      path: "/api/v1/projects/{projectId}/rfis/{rfiId}",
      params: ["projectId", "rfiId"],
    });
    expect(toOpenApiPath("/api/v1/health")).toEqual({ path: "/api/v1/health", params: [] });
  });
});

describe("tagging", () => {
  it("tags a project-scoped route by its AREA, not by 'projects'", () => {
    expect(tagForPath("/api/v1/projects/:projectId/rfis", "/api/v1")).toBe("rfis");
    expect(tagForPath("/api/v1/projects/:projectId/analytics/forecast", "/api/v1")).toBe(
      "analytics",
    );
  });

  it("tags a company route by its first segment", () => {
    expect(tagForPath("/api/v1/integrations/webhooks", "/api/v1")).toBe("integrations");
    expect(tagForPath("/api/v1/projects", "/api/v1")).toBe("projects");
  });
});

describe("buildOpenApiDocument", () => {
  const doc = buildOpenApiDocument({
    title: "ConstructOS API",
    version: "1",
    prefix: "/api/v1",
    serverUrl: "https://example.test",
    routes: parseRouteTree(TREE),
  });

  it("produces a 3.1 document with one path item per route", () => {
    expect(doc.openapi).toBe("3.1.0");
    expect(Object.keys(doc.paths)).toContain("/api/v1/analytics/reports/{reportId}");
    const item = doc.paths["/api/v1/analytics/reports/{reportId}"]!;
    expect(Object.keys(item).sort()).toEqual(["delete", "get", "parameters", "patch"]);
  });

  it("declares path parameters as required strings", () => {
    const item = doc.paths["/api/v1/projects/{projectId}/analytics/forecast"]!;
    expect(item["parameters"]).toEqual([
      { name: "projectId", in: "path", required: true, schema: { type: "string" } },
    ]);
  });

  it("declares both the human and the machine authentication schemes", () => {
    const schemes = (doc.components["securitySchemes"] ?? {}) as Record<string, unknown>;
    expect(Object.keys(schemes).sort()).toEqual(["bearerAuth", "companyHeader", "oauth2"]);
    expect(doc.security).toEqual([{ bearerAuth: [], companyHeader: [] }, { oauth2: [] }]);
  });

  it("says plainly that bodies are not published as JSON Schema", () => {
    const description = String(doc.info["description"]);
    expect(description).toContain("NOT published here as JSON");
    expect(description).toContain("GENERATED FROM THE LIVE ROUTE TABLE");
  });

  it("gives every operation a unique operationId", () => {
    const ids: string[] = [];
    for (const item of Object.values(doc.paths)) {
      for (const [method, op] of Object.entries(item)) {
        if (method === "parameters") continue;
        ids.push(String((op as Record<string, unknown>)["operationId"]));
      }
    }
    expect(new Set(ids).size).toBe(ids.length);
  });

  it("tags every operation and lists the tags", () => {
    expect(doc.tags.map((t) => t.name)).toEqual(["analytics", "integrations"]);
  });
});
